baseURL = ""
languageCode = "en-us"
title = "The Photogrammer"
theme = "aether"
googleAnalytics = "UA-128690897-1"
disqusShortname = "barsonaxblog"

[params]
brand = "The Photogrammer"
description = "A blog about coding and photography"
bgimg = "images/ignasipattern.png"
rssinmenu = true