[build]
publish = "public"
command = "hugo -b $URL --gc --minify"

[build.environment]
  HUGO_VERSION = "0.55.6"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[[headers]]
  for = "*.png"
  [headers.values]
	  cache-control = '''
    public,
	  max-age=604800'''